import Head from 'next/head'
// import Image from 'next/image'
import Nav from '../component/nav'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
<div className={styles.container} >
     <Nav/>
      <Head>
        <title>Inner Ease</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="/tailwind.css" />

      </Head>
      <main className={`${styles.main} ${inter.className}`}>
          
          <div className={styles.hed} >
            <h1>"There is no health without mental health."</h1>
            <p> - U.S. First Lady Rosalynn Carter</p>

            <br/><br/><br/><br/>
            <h3>
            The term "mental health care" describes a broad variety of treatments and activities intended to treat people who are struggling with mental health issues, prevent the emergence or recurrence of mental health illnesses, and promote and sustain mental well-being. It includes a range of approaches meant to deal with a person's emotional, psychological, and social needs.
            </h3>
          </div>
        <div className={styles.description}>
          <a
            href="https://www.mindgames.com/Brain+Games"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            {/* <h2>
              Docs <span>-&gt;</span>
            </h2> */}
            <p>
            The Path to Relaxation and Pleasure.
            </p>
          </a>

          <a
            href="/blog"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
        
            <p>
            Raising Awareness of Mental Health Services 
            </p>
          </a>

         

          
        </div>

        
      </main>
      </div>
    </>
  )
}
